# install Logstash by OS_family
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure Logstash
- name: enable ipaddress
  lineinfile:
    path: /etc/logstash/logstash.yml
    regexp: '#http.host: "127.0.0.1"'
    line: 'http.host: 0.0.0.0'
    state: present


- name: http.port
  lineinfile:
    path: /etc/logstash/logstash.yml
    regexp: '#http.port: 9600-9700'
    line: 'http.port: 9600-9700'
    state: present

- name: run logstash
  shell: /usr/share/logstash/bin/logstash -e 'input { stdin { } } output { stdout {} }'

- name: Restart logstash
  service:
    name: logstash.service
    state: restarted
    enabled: yes

# set soft link, -f enforce the exist links
# ln -sf src des
- name: set soft link
  shell: |
    ln -sf /var/log/logstash  /data/log/
    ln -sf /etc/logstash/logstash.yml /data/config/

# Check version,
# must use sudo sh -c to solve the no-root permission
- block:
  - name: Check Logstash Version
    shell: sudo sh -c "rabbitmqctl status | grep 'Logstash version' 1>> /data/logs/install_version.txt"

# check service state
- name: Check Logstash Service
  shell: systemctl status logstash | grep Active*
  register: check_logstash_service
  notify: check_logstash_service
